# Based on https://github.com/PrakashTrove/AWS-CodeBuild-NetCore/blob/master/buildspec.yml
# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: latest
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore TransactionImporter/TransactionImporter.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build TransactionImporter/TransactionImporter.csproj
      
  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -c release -o ./build_output TransactionImporter/TransactionImporter.csproj
      
artifacts:
  files:
    - '**/*'
  base-directory: './build_output'
  discard-paths: no